CREATE DATABASE sistema;
use sistemas;
CREATE TABLE PLANTA(
IDPLANT INT NOT NULL AUTO_INCREMENT COMMENT "ID DE LOS TIPOS DE PLANTA",
NOMPLANT VARCHAR(50) NULL COMMENT "NOMBRE DE LA PLANTA",
CONSTRAINT PLANTA_PK PRIMARY KEY(IDPLANT)

);
CREATE TABLE DATOS(
IDRIEG INT NOT NULL AUTO_INCREMENT COMMENT "ID DELOS DATOS EVENTUALES DEL CLIMA Y DE LA H DEL SUELO",
IDPLANT INT NOT NULL COMMENT "IDENTIFICADOR DE TIPO DE PLANTA",
IDAQUAS INT NOT NULL COMMENT "IDENTIFICADOR DE LA TABLA AQUAS",
DATALM35 INT NOT NULL COMMENT "DATA QUE DEVUELVE EL SENSOR DE CLIMA",
DATAYL69 INT NOT NULL comment "DATA QUE DEVUELVE EL SENSOR DEL SUELO",
CONSTRAINT DATOS_PK PRIMARY KEY (IDRIEG)
);
CREATE TABLE AQUAS(
IDAQUAS INT NOT NULL AUTO_INCREMENT,
LITAQ INT NOT NULL,
FECHRIEG datetime NOT NULL,
HORARIEG INT NOT NULL,
CONSTRAINT AQUAS_PK PRIMARY KEY (IDAQUAS) 
);
ALTER TABLE DATOS ADD CONSTRAINT DATOS_PLANTA foreign key DATOS_PLANTA (IDPLANT)
REFERENCES PLANTA (IDPLANT);
ALTER TABLE DATOS ADD CONSTRAINT DATOS_AQUAS FOREIGN KEY DATOS_AQUAS (IDAQUAS) 
references PLANTA (IDAQUAS);


